/**
 * @file main.c
 * @brief ROTS Receiver Main Application
 * @author ROTS Team
 * @date 2024
 * 
 * Main application entry point for STM32F407VET6 receiver
 */

#include "rots_receiver.h"
#include "rots_communication.h"
#include "rots_actuator_control.h"
#include "rots_recipe_manager.h"
#include "rots_display.h"
#include "rots_system_monitor.h"
#include "rots_debug.h"
#include "rots_hardware.h"
#include "rots_spi_flash.h"

static ROTS_StatusTypeDef ROTS_SystemInit(void);
static void ROTS_MainLoop(void);
static void ROTS_ErrorHandler(ROTS_StatusTypeDef error_code);

/**
 * @brief Main function
 * @return Always 0
 */
int main(void)
{
    ROTS_StatusTypeDef status;
    
    /* Initialize system */
    status = ROTS_SystemInit();
    if (status != ROTS_OK) {
        ROTS_ErrorHandler(status);
    }
    
    /* Display startup message */
    ROTS_Display_ShowMessage("ROTS Receiver", "Initializing...");
    
    /* Main application loop */
    ROTS_MainLoop();
    
    return 0;
}

/**
 * @brief Initialize system
 * @return ROTS_OK if successful, error code otherwise
 */
static ROTS_StatusTypeDef ROTS_SystemInit(void)
{
    ROTS_StatusTypeDef status = ROTS_OK;
    
    /* Initialize HAL library */
    HAL_Init();
    
    /* Configure system tick timer */
    SystemClock_Config();
    
    /* Initialize system clock */
    status = ROTS_SystemClock_Init();
    if (status != ROTS_OK) return status;
    
    /* Initialize hardware peripherals */
    status = ROTS_GPIO_Init();
    if (status != ROTS_OK) return status;
    
    status = ROTS_PWM_Init();
    if (status != ROTS_OK) return status;
    
    status = ROTS_UART_Init();
    if (status != ROTS_OK) return status;
    
    status = ROTS_I2C_Init();
    if (status != ROTS_OK) return status;
    
    status = ROTS_ADC_Init();
    if (status != ROTS_OK) {
        DEBUG_WARNING("ADC init failed, continuing without ADC\r\n");
    }
    
    /* Initialize SPI Flash */
    status = ROTS_SPI_Flash_Init();
    if (status != ROTS_OK) {
        DEBUG_WARNING("SPI Flash init failed, continuing without flash storage\r\n");
    }
    
    /* Initialize debug system */
    status = ROTS_Debug_Init();
    if (status != ROTS_OK) return status;
    
    DEBUG_INFO("ROTS Receiver Starting...\r\n");
    
    /* Perform hardware self-test */
    status = ROTS_Hardware_SelfTest();
    if (status != ROTS_OK) return status;
    
    /* Initialize communication module */
    status = ROTS_Communication_Init();
    if (status != ROTS_OK) {
        DEBUG_ERROR("Communication init failed\r\n");
        return status;
    }
    
    /* Initialize actuator control */
    status = ROTS_ActuatorControl_Init();
    if (status != ROTS_OK) {
        DEBUG_ERROR("Actuator control init failed\r\n");
        return status;
    }
    
    /* Initialize recipe manager */
    status = ROTS_RecipeManager_Init();
    if (status != ROTS_OK) {
        DEBUG_ERROR("Recipe manager init failed\r\n");
        return status;
    }
    
    /* Initialize display */
    status = ROTS_Display_Init();
    if (status != ROTS_OK) {
        DEBUG_ERROR("Display init failed\r\n");
        return status;
    }
    
    /* Initialize system monitor */
    status = ROTS_SystemMonitor_Init();
    if (status != ROTS_OK) {
        DEBUG_ERROR("System monitor init failed\r\n");
        return status;
    }
    
    DEBUG_INFO("System initialization completed\r\n");
    return ROTS_OK;
}

/**
 * @brief System clock configuration
 * @note This function is typically generated by STM32CubeMX
 */
void SystemClock_Config(void)
{
    /* System clock configuration is handled by ROTS_SystemClock_Init() */
    /* This function is kept for compatibility with HAL library */
}

/**
 * @brief Main application loop
 */
static void ROTS_MainLoop(void)
{
    ROTS_MessageTypeDef received_msg;
    ROTS_StatusTypeDef status;
    uint32_t last_debug_time = 0;
    uint32_t last_status_time = 0;
    uint32_t last_status_send_time = 0;
    uint32_t last_display_update_time = 0;
    uint32_t last_heartbeat_time = 0;
    
    DEBUG_INFO("Entering main loop\r\n");
    
    while (1) {
        /* Update communication module (check for incoming messages) */
        ROTS_Communication_Update();
        
        /* Check for incoming messages */
        status = ROTS_Communication_ReceiveMessage(&received_msg);
        if (status == ROTS_OK) {
            DEBUG_INFO("Received message\r\n");
            ROTS_Debug_PrintMessage(&received_msg);
            
            /* Process received odor command */
            status = ROTS_ActuatorControl_ProcessOdorCommand(&received_msg);
            if (status != ROTS_OK) {
                DEBUG_ERROR("Failed to process command: %d\r\n", status);
                /* Send error status back to cloud server */
                ROTS_Communication_SendError(status);
            } else {
                /* Send success status */
                ROTS_SystemStatus_t system_status;
                ROTS_SystemMonitor_GetStatus(&system_status);
                ROTS_Communication_SendStatus(&system_status);
            }
        } else if (status == ROTS_COMM_ERROR) {
            DEBUG_ERROR("Communication error\r\n");
        }
        
        /* Update system status every 1 second */
        if ((HAL_GetTick() - last_status_time) >= 1000) {
            ROTS_SystemMonitor_Update();
            last_status_time = HAL_GetTick();
        }
        
        /* Send periodic status update every 5 seconds */
        if ((HAL_GetTick() - last_status_send_time) >= 5000) {
            ROTS_SystemStatus_t system_status;
            ROTS_SystemMonitor_GetStatus(&system_status);
            ROTS_Communication_SendStatus(&system_status);
            last_status_send_time = HAL_GetTick();
        }
        
        /* Send heartbeat every 30 seconds */
        if ((HAL_GetTick() - last_heartbeat_time) >= 30000) {
            /* Send heartbeat via MQTT */
            ROTS_SystemStatus_t system_status;
            ROTS_SystemMonitor_GetStatus(&system_status);
            ROTS_Communication_SendStatus(&system_status);
            last_heartbeat_time = HAL_GetTick();
        }
        
        /* Update actuator control (check timer expiration) */
        ROTS_ActuatorControl_Update();
        
        /* Update display every 500ms */
        if ((HAL_GetTick() - last_display_update_time) >= 500) {
            ROTS_Display_Update();
            last_display_update_time = HAL_GetTick();
        }
        
        /* Print debug info every 10 seconds */
        if ((HAL_GetTick() - last_debug_time) >= 10000) {
            ROTS_Debug_PrintSystemStatus();
            ROTS_Debug_PrintWiFiStatus();
            ROTS_Debug_PrintMQTTStatus();
            ROTS_Debug_PrintMemoryUsage();
            last_debug_time = HAL_GetTick();
        }
        
        /* Small delay to prevent CPU overload */
        HAL_Delay(10);
    }
}

/**
 * @brief Error handler
 * @param error_code Error code
 */
static void ROTS_ErrorHandler(ROTS_StatusTypeDef error_code)
{
    /* Display error on screen */
    ROTS_Display_ShowError(error_code);
    
    /* Log error to system monitor */
    ROTS_SystemMonitor_LogError(error_code);
    
    /* Send error to cloud server */
    ROTS_Communication_SendError(error_code);
    
    /* Enter error state loop */
    while (1) {
        /* Blink error LED to indicate error */
        HAL_GPIO_TogglePin(ERROR_LED_PORT, ERROR_LED_PIN);
        HAL_Delay(500);
        
        /* Try to recover after some time */
        /* Real system would have recovery logic */
        static uint32_t recovery_attempts = 0;
        if (recovery_attempts++ > 10) {
            /* Reset system after multiple recovery attempts */
            NVIC_SystemReset();
        }
    }
}
